# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.ganga.com:
  peer0.zudexo.yamuna.com:
  peer0.fci.saraswati.gov:
  peer0.ziggy.bhagirathi.com:
  peer0.sabkabazzar.jhelum.com:

networks:
  annpurna:

services:

  orderer.ganga.com:
    container_name: orderer.ganga.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=8051
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - /home/atri/workspace_hlf/annpurna/network/system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - /home/atri/workspace_hlf/annpurna/organizations/orderer/organization/ordererOrganizations/orderer.ganga.com/orderers/orderer.ganga.com/msp:/var/hyperledger/orderer/msp
        - /home/atri/workspace_hlf/annpurna/organizations/orderer/organization/ordererOrganizations/orderer.ganga.com/orderers/orderer.ganga.com/tls/:/var/hyperledger/orderer/tls
        - orderer.ganga.com:/var/hyperledger/production/orderer
    ports:
      - 8051:8051
    networks:
      - annpurna

  peer0.zudexo.yamuna.com:
    container_name: peer0.zudexo.yamuna.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_annpurna
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.zudexo.yamuna.com
      - CORE_PEER_ADDRESS=peer0.zudexo.yamuna.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.zudexo.yamuna.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.zudexo.yamuna.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.zudexo.yamuna.com:7051
      - CORE_PEER_LOCALMSPID=ZudexoMSP
    volumes:
        - /var/run/:/host/var/run/
        - /home/atri/workspace_hlf/annpurna/organizations/zudexo/organization/peerOrganizations/zudexo.yamuna.com/peers/peer0.zudexo.yamuna.com/msp:/etc/hyperledger/fabric/msp
        - /home/atri/workspace_hlf/annpurna/organizations/zudexo/organization/peerOrganizations/zudexo.yamuna.com/peers/peer0.zudexo.yamuna.com/tls:/etc/hyperledger/fabric/tls
        - peer0.zudexo.yamuna.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
    networks:
      - annpurna

  peer0.fci.saraswati.gov:
    container_name: peer0.fci.saraswati.gov
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_annpurna
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.fci.saraswati.gov
      - CORE_PEER_ADDRESS=peer0.fci.saraswati.gov:7151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7151
      - CORE_PEER_CHAINCODEADDRESS=peer0.fci.saraswati.gov:7152
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7152
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.fci.saraswati.gov:7151
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.fci.saraswati.gov:7151
      - CORE_PEER_LOCALMSPID=FciMSP
    volumes:
        - /var/run/:/host/var/run/
        - /home/atri/workspace_hlf/annpurna/organizations/fci/organization/peerOrganizations/fci.saraswati.gov/peers/peer0.fci.saraswati.gov/msp:/etc/hyperledger/fabric/msp
        - /home/atri/workspace_hlf/annpurna/organizations/fci/organization/peerOrganizations/fci.saraswati.gov/peers/peer0.fci.saraswati.gov/tls:/etc/hyperledger/fabric/tls
        - peer0.fci.saraswati.gov:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7151:7151
    networks:
      - annpurna

  peer0.ziggy.bhagirathi.com:
    container_name: peer0.ziggy.bhagirathi.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_annpurna
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.ziggy.bhagirathi.com
      - CORE_PEER_ADDRESS=peer0.ziggy.bhagirathi.com:7251
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7251
      - CORE_PEER_CHAINCODEADDRESS=peer0.ziggy.bhagirathi.com:7252
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7252
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ziggy.bhagirathi.com:7251
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ziggy.bhagirathi.com:7251
      - CORE_PEER_LOCALMSPID=ZiggyMSP
    volumes:
        - /var/run/:/host/var/run/
        - /home/atri/workspace_hlf/annpurna/organizations/ziggy/organization/peerOrganizations/ziggy.bhagirathi.com/peers/peer0.ziggy.bhagirathi.com/msp:/etc/hyperledger/fabric/msp
        - /home/atri/workspace_hlf/annpurna/organizations/ziggy/organization/peerOrganizations/ziggy.bhagirathi.com/peers/peer0.ziggy.bhagirathi.com/tls:/etc/hyperledger/fabric/tls
        - peer0.ziggy.bhagirathi.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7251:7251
    networks:
      - annpurna

  peer0.sabkabazzar.jhelum.com:
    container_name: peer0.sabkabazzar.jhelum.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_annpurna
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.sabkabazzar.jhelum.com
      - CORE_PEER_ADDRESS=peer0.sabkabazzar.jhelum.com:7351
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7351
      - CORE_PEER_CHAINCODEADDRESS=peer0.sabkabazzar.jhelum.com:7352
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7352
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.sabkabazzar.jhelum.com:7351
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.sabkabazzar.jhelum.com:7351
      - CORE_PEER_LOCALMSPID=SabkabazzarMSP
    volumes:
        - /var/run/:/host/var/run/
        - /home/atri/workspace_hlf/annpurna/organizations/sabkabazzar/organization/peerOrganizations/sabkabazzar.jhelum.com/peers/peer0.sabkabazzar.jhelum.com/msp:/etc/hyperledger/fabric/msp
        - /home/atri/workspace_hlf/annpurna/organizations/sabkabazzar/organization/peerOrganizations/sabkabazzar.jhelum.com/peers/peer0.sabkabazzar.jhelum.com/tls:/etc/hyperledger/fabric/tls
        - peer0.sabkabazzar.jhelum.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7351:7351
    networks:
      - annpurna
      