# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  annpurna:

services:

  ca_zudexo:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-zudexo
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - /home/atri/workspace_hlf/annpurna/organizations/zudexo/fabric-ca:/etc/hyperledger/fabric-ca-server
    container_name: ca_zudexo
    networks:
      - annpurna

  ca_fci:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-fci
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7154
    ports:
      - "7154:7154"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - /home/atri/workspace_hlf/annpurna/organizations/fci/fabric-ca:/etc/hyperledger/fabric-ca-server
    container_name: ca_fci
    networks:
      - annpurna

  ca_ziggy:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-ziggy
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7254
    ports:
      - "7254:7254"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - /home/atri/workspace_hlf/annpurna/organizations/ziggy/fabric-ca:/etc/hyperledger/fabric-ca-server
    container_name: ca_ziggy
    networks:
      - annpurna
      
  ca_sabkabazzar:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-sabkabazzar
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7354
    ports:
      - "7354:7354"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - /home/atri/workspace_hlf/annpurna/organizations/sabkabazzar/fabric-ca:/etc/hyperledger/fabric-ca-server
    container_name: ca_sabkabazzar
    networks:
      - annpurna



  ca_orderer:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - /home/atri/workspace_hlf/annpurna/organizations/orderer/fabric-ca:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer
    networks:
      - annpurna
